# Generated by Django 5.2.5 on 2025-09-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=200, null=True)),
                ('image', models.ImageField(default=None, upload_to='menu_images/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
